### ISSUE TITLE
Can't build game

### ISSUE THREAD

**Issue by ghost** [joekarl/swift_handmade_hero#1]
Hey there,

Thanks for making this. I did exactly what you said but still can't get it to work. I downloaded this, downloaded the day you state in README. Then copy files over and try to build but I get this issue:

http://cl.ly/image/02183Y133x0S

It's as though OpenGL isn't "installed" or something. Any ideas?

**Comment by joekarl** [comment]
Hmm interesting. It looks like the pixelformat isn't initialized.
Can you show what the address of the pixelformat is when the error occurs?

**Comment by joekarl** [comment]
Also what machine are you running on? (MacBook pro? Mac mini? Mac Pro?)

**Comment by ghost** [comment]
Macbook Air running the latest OSX. How do I look up an 'address'? Im not sure what that means. I tried to LOG the pixelFormat variable but it seems to not work. I think that is the variable that is missing and returning nil? I assume there is a way to create 'watchers' in Xcode like you would in other IDE's to watch variables. That's what you mean?

**Comment by joekarl** [comment]
Yeah basically you can look in the 'self' object in you variables window and there should be an entry for pixel format somewhere in there. 
But I think we pretty much both came to the conclusion that the pixelformat is null :/ so don't need the address now (it should be 0x000000000 if it's a null pointer). 

So it appears that your machine doesn't like the pixelformat attributes that gameview is requesting. It's probably going to be the depth buffer (which we probably don't need anyways) or the accelerated renderer attribute. 

Can you see what happens if you remove the depth buffer attribute? (The name and the number from the pfa array)

**Comment by ghost** [comment]
When I remove the double buffer AND the accelerated items from array it renders this: 
http://cl.ly/image/2A0f343t3R0I

When I remove one or the other only, it throws an error in the same line of code. I should note if I remove those I can't move around the screen but maybe in this version of the game via casey's code that isn't coded up yet? So perhaps that is desired functionality. 

I also should note that when I view the SELF object in the logger when I get the error I see there is some data in the pixel format attributes array
http://cl.ly/image/0C3V2q0A3b2C

So perhaps it isn't null like we thought? Or that isn't the issue? Hmmm

**Comment by joekarl** [comment]
Oops my bad, that's the pixelformatattr array ;) the pixel format will be buried in self->NSOpenGlView->pixelFormat. 

As for the rendering, that's interesting...
It appears that the air doesn't support double buffering or hardware accelerated rendering o_0 may have to dig some more to figure out what's going on there...

It should allow movement as well (though I'm not super confident that all of the HID input stuff is hooked up correctly). The movement keys are the awsd keys (corresponds to what Casey has in his platform layer). 

Let me throw together a vid to show what it looks like running as of right now.

**Comment by ghost** [comment]
Ah, alright man. And no worries if the air doesn't support this. I'll just try to spin up a windows virtual machine or something :)

Thanks for all your help

**Comment by joekarl** [comment]
So it can fallback to the non accelerated drawing (this is fine for now) and double buffering isn't strictly required either. 
I added a glFlush inside of the render loop which should allow working in a single buffer context. Pull that update and see if it fixes things for you.

**Comment by joekarl** [comment]
Ah, see yeah, I should read things. Apple says to call glFlush() and then glContext.flushBuffer() as flushBuffer only works for double buffered contexts. (http://stackoverflow.com/questions/7027346/glflush-vs-self-openglcontext-flushbuffer-vs-glfinish-vs-glswapapple-vs-ag)

So anyways, I just pushed another update that will allow the code to attempt to get a double buffered accelerated context, if that fails it will try to grab a single buffered context, and if THAT fails it'll puke lol.

Let me know if that solves things for you :)
